version: 2
jobs:
  test:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Instal dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            yarn test --ci --coverage --maxWorkers=2
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
  deploy_staging:
    docker:
      - image: circleci/ruby:2.5.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install dpl
      - run:
          name: Deploy to staging
          command: |
            dpl --provider=heroku --app=gcer-web --api-key=$HEROKU_API_KEY
  deploy_production:
    docker:
      - image: circleci/ruby:2.5.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install dpl
      - run:
          name: Deploy to production
          command: |
            dpl --provider=heroku --app=gcer-web --api-key=$HEROKU_API_KEY
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          context: org-global
          filters:
            tags:
              ignore: /.*/
      - deploy_staging:
          context: org-global
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
          requires:
            - test
      - deploy_production:
          context: org-global
          filters:
            tags:
              only: /v[0-9]+/
            branches:
              ignore: /.*/
